apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: My automation
on:
  workflow_dispatch:
jobs:
  deploy:
    steps:
      - uses: cloudbees-io/checkout@v1
        name: checkout

      - id: dockerconfig
        name: Configure container registry credentials
        uses: cloudbees-io/configure-oci-credentials@v1
        with:
          registry: ${{ vars.DOCKER_REGISTRY }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - uses: cloudbees-io/kaniko/.cloudbees/testing
        name: Push image to OCI registry
        with:
          destination: ghcr.io/cbpautomation/python-hello-world-docker:${{cloudbees.version}}
          labels: app=cbp

      - name: Dislay Artifact Version
        uses: docker://golang:1.20.3-alpine3.17
        shell: sh
        run: |
          echo "CB_VERSION: ${{cloudbees.version}}"





