apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: RegisterDeployedArtifact
on:
  workflow_dispatch:
jobs:
  env_reg_artifacts:
    steps:
      - name: success_valid_env_reg_artifact
        uses: cloudbees-io/register-deployed-artifact@v1
        with:
          name: "cbpautomation/python-hello-world-docker"
          version: "25.16.28"
          digest: "sha256:f7bda9d11a958a12955da9c7b1835caf2f4cd3438fb3150823f76369f0e9e904"
          url: "docker.io/cbpautomation/python-hello-world-docker:25.16.28"
          target-environment: "QA"

