apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: RegisterDeployedArtifact
on:
  workflow_dispatch:
jobs:
  env_reg_artifacts:
    steps:
      - name: success_valid_env_reg_artifact
        uses: cloudbees-io/register-deployed-artifact@v1
        with:
          name: "cbpautomation/python-hello-world-docker"
          version: "23.04.29"
          digest: "sha256:a5327ce5ffbd31fe41a89081cc3df18569432f2216cd793cd4f001a6dec6511b"
          url: "docker.io/cbpautomation/python-hello-world-docker:23.04.29"
          target-environment: "QA"

