apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: RegisterDeployedArtifact
on:
  workflow_dispatch:
jobs:
  env_reg_artifacts:
    steps:
      - name: Inform system that an artifact version was created
        uses: cloudbees-io/register-build-artifact@v1
        with:
          name: "cbpautomation/python-hello-world-docker"
          version: "20.10.34"
          url: "docker.io/cbpautomation/python-hello-world-docker:20.10.34"
          digest: "sha256:175cc3d4a5a0b129eebf049cb0801d4e7b01bbec13c169e5ed606af719c4f773"
          
      - name: success_valid_env_reg_artifact
        uses: cloudbees-io/register-deployed-artifact@v1
        with:
          name: "cbpautomation/python-hello-world-docker"
          version: "20.10.34"
          digest: "sha256:175cc3d4a5a0b129eebf049cb0801d4e7b01bbec13c169e5ed606af719c4f773"
          url: "docker.io/cbpautomation/python-hello-world-docker:20.10.34"
          target-environment: "QA"

