apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: RegisterDeployedArtifact
on:
  workflow_dispatch:
jobs:
  env_reg_artifacts:
    steps:
      - name: success_valid_env_reg_artifact
        uses: cloudbees-io/register-deployed-artifact@v1
        with:
          name: "cbpautomation/python-hello-world-docker"
          version: "11.16.23"
          digest: "sha256:7516518f71c8f1f2630dd325c431169d56a6637acc6c13dbb3b2e3c1a9a0e060"
          url: "docker.io/cbpautomation/python-hello-world-docker:11.16.23"
          target-environment: "QA"

