apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: RegisterDeployedArtifact
on:
  workflow_dispatch:
jobs:
  env_reg_artifacts:
    steps:
      - name: Inform system that an artifact version was created
        uses: cloudbees-io/register-build-artifact@v1
        with:
          name: "cbpautomation/python-hello-world-docker"
          version: "02.10.21"
          url: "docker.io/cbpautomation/python-hello-world-docker:02.10.21"
          digest: "sha256:87ee79baff25a358bfe480bebd6414f576d701bc640dc5d602c204eb2fe3161b"
          
      - name: success_valid_env_reg_artifact
        uses: cloudbees-io/register-deployed-artifact@v1
        with:
          name: "cbpautomation/python-hello-world-docker"
          version: "02.10.21"
          digest: "sha256:87ee79baff25a358bfe480bebd6414f576d701bc640dc5d602c204eb2fe3161b"
          url: "docker.io/cbpautomation/python-hello-world-docker:02.10.21"
          target-environment: "QA"

