apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: RegisterDeployedArtifact
on:
  workflow_dispatch:
jobs:
  env_reg_artifacts:
    steps:
      - name: success_valid_env_reg_artifact
        uses: cloudbees-io/register-deployed-artifact@v1
        with:
          name: "cbpautomation/python-hello-world-docker"
          version: "28.10.37"
          digest: "sha256:322bc84a73d3a0edfed5ee7272eff846704263d53a04f9d1769e233123b73e32"
          url: "docker.io/cbpautomation/python-hello-world-docker:28.10.37"
          target-environment: "QA"

