apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: RegisterDeployedArtifact
on:
  workflow_dispatch:
jobs:
  env_reg_artifacts:
    steps:
      - name: Inform system that an artifact version was created
        uses: cloudbees-io/register-build-artifact@v1
        with:
          name: "cbpautomation/python-hello-world-docker"
          version: "02.10.39"
          url: "docker.io/cbpautomation/python-hello-world-docker:02.10.39"
          digest: "sha256:ccb4f64c27ab581aeb15e419956616cfdeca9f962575acaa570a37736937bfce"
          
      - name: success_valid_env_reg_artifact
        uses: cloudbees-io/register-deployed-artifact@v1
        with:
          name: "cbpautomation/python-hello-world-docker"
          version: "02.10.39"
          digest: "sha256:ccb4f64c27ab581aeb15e419956616cfdeca9f962575acaa570a37736937bfce"
          url: "docker.io/cbpautomation/python-hello-world-docker:02.10.39"
          target-environment: "QA"

