apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: RegisterDeployedArtifact
on:
  workflow_dispatch:
jobs:
  env_reg_artifacts:
    steps:
      - name: success_valid_env_reg_artifact
        uses: cloudbees-io/register-deployed-artifact@v1
        with:
          name: "cbpautomation/python-hello-world-docker"
          version: "29.13.59"
          digest: "sha256:3927e85a5a1d8bc22611d8c93ae92a7d397735aebeb837b95e6f88f0fb7b5e39"
          url: "docker.io/cbpautomation/python-hello-world-docker:29.13.59"
          target-environment: "QA"

