apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: RegisterDeployedArtifact
on:
  workflow_dispatch:
jobs:
  env_reg_artifacts:
    steps:
      - name: Inform system that an artifact version was created
        uses: cloudbees-io/register-build-artifact@v1
        with:
          name: "cbpautomation/python-hello-world-docker"
          version: "13.10.26"
          url: "docker.io/cbpautomation/python-hello-world-docker:13.10.26"
          digest: "sha256:a3bc4258405625f4b5889e2ac64e4eee297e2315e1dc9352db55f049390b8fe5"
          
      - name: success_valid_env_reg_artifact
        uses: cloudbees-io/register-deployed-artifact@v1
        with:
          name: "cbpautomation/python-hello-world-docker"
          version: "13.10.26"
          digest: "sha256:a3bc4258405625f4b5889e2ac64e4eee297e2315e1dc9352db55f049390b8fe5"
          url: "docker.io/cbpautomation/python-hello-world-docker:13.10.26"
          target-environment: "QA"

