apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: RegisterDeployedArtifact
on:
  workflow_dispatch:
jobs:
  env_reg_artifacts:
    steps:
      - name: Inform system that an artifact version was created
        uses: cloudbees-io/register-build-artifact@v1
        with:
          name: "cbpautomation/python-hello-world-docker"
          version: "14.10.36"
          url: "docker.io/cbpautomation/python-hello-world-docker:14.10.36"
          digest: "sha256:386e99b141f89133cc67ac8bb4c966f8a75261bcfe78f5f23cb9efbaec621915"
          
      - name: success_valid_env_reg_artifact
        uses: cloudbees-io/register-deployed-artifact@v1
        with:
          name: "cbpautomation/python-hello-world-docker"
          version: "14.10.36"
          digest: "sha256:386e99b141f89133cc67ac8bb4c966f8a75261bcfe78f5f23cb9efbaec621915"
          url: "docker.io/cbpautomation/python-hello-world-docker:14.10.36"
          target-environment: "QA"

