apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: RegisterDeployedArtifact
on:
  workflow_dispatch:
jobs:
  env_reg_artifacts:
    steps:
      - name: success_valid_env_reg_artifact
        uses: cloudbees-io/register-deployed-artifact@v1
        with:
          name: "cbpautomation/python-hello-world-docker"
          version: "22.16.29"
          digest: "sha256:ffcd20e45414d6db7d5a0ec5df998f8028189f12774b9f43126ef67593f6c492"
          url: "docker.io/cbpautomation/python-hello-world-docker:22.16.29"
          target-environment: "QA"

