apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: RegisterDeployedArtifact
on:
  workflow_dispatch:
jobs:
  env_reg_artifacts:
    steps:
      - name: success_valid_env_reg_artifact
        uses: cloudbees-io/register-deployed-artifact@v1
        with:
          name: "cbpautomation/python-hello-world-docker"
          version: "23.13.06"
          digest: "sha256:ad41d9487482eed30890529c1a197ed0a7cbb9b66ae2120633f80d62e95ffc14"
          url: "docker.io/cbpautomation/python-hello-world-docker:23.13.06"
          target-environment: "QA"

