apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: RegisterDeployedArtifact
on:
  workflow_dispatch:
jobs:
  env_reg_artifacts:
    steps:
      - name: success_valid_env_reg_artifact
        uses: cloudbees-io/register-deployed-artifact@v1
        with:
          name: "cbpautomation/python-hello-world-docker"
          version: "28.16.33"
          digest: "sha256:48fce1a9952137582381e718e4009a973f6d94c2facd602fe56ef1268d9418e5"
          url: "docker.io/cbpautomation/python-hello-world-docker:28.16.33"
          target-environment: "QA"

