apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: RegisterDeployedArtifact
on:
  workflow_dispatch:
jobs:
  env_reg_artifacts:
    steps:
      - name: Inform system that an artifact version was created
        uses: cloudbees-io/register-build-artifact@v1
        with:
          name: "cbpautomation/python-hello-world-docker"
          version: "02.10.23"
          url: "docker.io/cbpautomation/python-hello-world-docker:02.10.23"
          digest: "sha256:45108db01f274b5f2a595df607ec8a0636b71e116fcdf0bf19351c7cc5e239df"
          
      - name: success_valid_env_reg_artifact
        uses: cloudbees-io/register-deployed-artifact@v1
        with:
          name: "cbpautomation/python-hello-world-docker"
          version: "02.10.23"
          digest: "sha256:45108db01f274b5f2a595df607ec8a0636b71e116fcdf0bf19351c7cc5e239df"
          url: "docker.io/cbpautomation/python-hello-world-docker:02.10.23"
          target-environment: "QA"

