apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: RegisterDeployedArtifact
on:
  workflow_dispatch:
jobs:
  env_reg_artifacts:
    steps:
      - name: Inform system that an artifact version was created
        uses: cloudbees-io/register-build-artifact@v1
        with:
          name: "cbpautomation/python-hello-world-docker"
          version: "30.14.18"
          url: "docker.io/cbpautomation/python-hello-world-docker:30.14.18"
          digest: "sha256:e589a104ce02bd3d692de477183a40b4e6d30ac3140349fdd3d5c9665d52c10c"
          
      - name: success_valid_env_reg_artifact
        uses: cloudbees-io/register-deployed-artifact@v1
        with:
          name: "cbpautomation/python-hello-world-docker"
          version: "30.14.18"
          digest: "sha256:e589a104ce02bd3d692de477183a40b4e6d30ac3140349fdd3d5c9665d52c10c"
          url: "docker.io/cbpautomation/python-hello-world-docker:30.14.18"
          target-environment: "QA"

