apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: RegisterDeployedArtifact
on:
  workflow_dispatch:
jobs:
  env_reg_artifacts:
    steps:
      - name: success_valid_env_reg_artifact
        uses: cloudbees-io/register-deployed-artifact@v1
        with:
          name: "cbpautomation/python-hello-world-docker"
          version: "18.04.28"
          digest: "sha256:37199c5001cc3a63fee00dc1fa1657d88a16b3f59ddac8b9dc7d50435d14ecac"
          url: "docker.io/cbpautomation/python-hello-world-docker:18.04.28"
          target-environment: "QA"

