apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: RegisterDeployedArtifact
on:
  workflow_dispatch:
jobs:
  env_reg_artifacts:
    steps:
      - name: success_valid_env_reg_artifact
        uses: cloudbees-io/register-deployed-artifact@v1
        with:
          name: "cbpautomation/python-hello-world-docker"
          version: "10.13.27"
          digest: "sha256:57efa1b2fb29ebce97d66fa8b6d834599a321623b104f5006d387ad510620605"
          url: "docker.io/cbpautomation/python-hello-world-docker:10.13.27"
          target-environment: "QA"

