apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: RegisterDeployedArtifact
on:
  workflow_dispatch:
jobs:
  env_reg_artifacts:
    steps:
      - name: Inform system that an artifact version was created
        uses: cloudbees-io/register-build-artifact@v1
        with:
          name: "cbpautomation/python-hello-world-docker"
          version: "30.11.11"
          url: "docker.io/cbpautomation/python-hello-world-docker:30.11.11"
          digest: "sha256:259272ca5a226bab9014dded9d38cbcc49a6bfa6e8d25d47dc63f6d1bbdd21b6"
          
      - name: success_valid_env_reg_artifact
        uses: cloudbees-io/register-deployed-artifact@v1
        with:
          name: "cbpautomation/python-hello-world-docker"
          version: "30.11.11"
          digest: "sha256:259272ca5a226bab9014dded9d38cbcc49a6bfa6e8d25d47dc63f6d1bbdd21b6"
          url: "docker.io/cbpautomation/python-hello-world-docker:30.11.11"
          target-environment: "QA"

