apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: RegisterDeployedArtifact
on:
  workflow_dispatch:
jobs:
  env_reg_artifacts:
    steps:
      - name: Inform system that an artifact version was created
        uses: cloudbees-io/register-build-artifact@v1
        with:
          name: "cbpautomation/python-hello-world-docker"
          version: "06.06.56"
          url: "docker.io/cbpautomation/python-hello-world-docker:06.06.56"
          digest: "sha256:fd97b9c2281685157fe7586a9d6aedd7aa91ab0c09eb856ca5c163ed841b00b6"
          
      - name: success_valid_env_reg_artifact
        uses: cloudbees-io/register-deployed-artifact@v1
        with:
          name: "cbpautomation/python-hello-world-docker"
          version: "06.06.56"
          digest: "sha256:fd97b9c2281685157fe7586a9d6aedd7aa91ab0c09eb856ca5c163ed841b00b6"
          url: "docker.io/cbpautomation/python-hello-world-docker:06.06.56"
          target-environment: "QA"

