apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: RegisterDeployedArtifact
on:
  workflow_dispatch:
jobs:
  env_reg_artifacts:
    steps:
      - name: success_valid_env_reg_artifact
        uses: cloudbees-io/register-deployed-artifact@v1
        with:
          name: "cbpautomation/python-hello-world-docker"
          version: "16.04.24"
          digest: "sha256:bbdd396aa3610d627f03969592d7e2b8805e47c35c31f9e0acba3b11a5d35691"
          url: "docker.io/cbpautomation/python-hello-world-docker:16.04.24"
          target-environment: "QA"

