apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: RegisterDeployedArtifact
on:
  workflow_dispatch:
jobs:
  env_reg_artifacts:
    steps:
      - name: success_valid_env_reg_artifact
        uses: cloudbees-io/register-deployed-artifact@v1
        with:
          name: "cbpautomation/python-hello-world-docker"
          version: "10.05.43"
          digest: "sha256:9cac1446e99a52eef6e54dd8c63379abeefc6531a44396413fdca6611a4287a5"
          url: "docker.io/cbpautomation/python-hello-world-docker:10.05.43"
          target-environment: "QA"

