apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: RegisterDeployedArtifact
on:
  workflow_dispatch:
jobs:
  env_reg_artifacts:
    steps:
      - name: success_valid_env_reg_artifact
        uses: cloudbees-io/register-deployed-artifact@v1
        with:
          name: "cbpautomation/python-hello-world-docker"
          version: "28.04.26"
          digest: "sha256:c6687450164501d423c8619207ce2e80dca2c005cec2ad03caf073dec9ffa650"
          url: "docker.io/cbpautomation/python-hello-world-docker:28.04.26"
          target-environment: "QA"

