apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: RegisterDeployedArtifact
on:
  workflow_dispatch:
jobs:
  env_reg_artifacts:
    steps:
      - name: success_valid_env_reg_artifact
        uses: cloudbees-io/register-deployed-artifact@v1
        with:
          name: "cbpautomation/python-hello-world-docker"
          version: "16.04.26"
          digest: "sha256:1360cec6bd5a87a4ae425453e6bba9710395e1263ed773fba4037bd85207da6f"
          url: "docker.io/cbpautomation/python-hello-world-docker:16.04.26"
          target-environment: "QA"

