apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: RegisterDeployedArtifact
on:
  workflow_dispatch:
jobs:
  env_reg_artifacts:
    steps:
      - name: success_valid_env_reg_artifact
        uses: cloudbees-io/register-deployed-artifact@v1
        with:
          name: "cbpautomation/python-hello-world-docker"
          version: "17.19.46"
          digest: "sha256:99776b13f03d837e1f6e9dd53ef1da1133e6ef8a2f12e21a3a63970b880a3a9c"
          url: "docker.io/cbpautomation/python-hello-world-docker:17.19.46"
          target-environment: "QA"

