apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: RegisterDeployedArtifact
on:
  workflow_dispatch:
jobs:
  env_reg_artifacts:
    steps:
      - name: success_valid_env_reg_artifact
        uses: cloudbees-io/register-deployed-artifact@v1
        with:
          name: "cbpautomation/python-hello-world-docker"
          version: "11.07.05"
          digest: "sha256:dd1764ffe95acdee451c980b2b395d8b4198c3ec62259628c1e71472b9e94af3"
          url: "docker.io/cbpautomation/python-hello-world-docker:11.07.05"
          target-environment: "QA"

