apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: RegisterDeployedArtifact
on:
  workflow_dispatch:
jobs:
  env_reg_artifacts:
    steps:
      - name: Inform system that an artifact version was created
        uses: cloudbees-io/register-build-artifact@v1
        with:
          name: "cbpautomation/python-hello-world-docker"
          version: "05.17.46"
          url: "docker.io/cbpautomation/python-hello-world-docker:05.17.46"
          digest: "sha256:30e85f4f9c4fe45ae6121bae7ad65b07002728131d3a0fa88a8183e9815aaaca"
          
      - name: success_valid_env_reg_artifact
        uses: cloudbees-io/register-deployed-artifact@v1
        with:
          name: "cbpautomation/python-hello-world-docker"
          version: "05.17.46"
          digest: "sha256:30e85f4f9c4fe45ae6121bae7ad65b07002728131d3a0fa88a8183e9815aaaca"
          url: "docker.io/cbpautomation/python-hello-world-docker:05.17.46"
          target-environment: "QA"

