apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: RegisterDeployedArtifact
on:
  workflow_dispatch:
jobs:
  env_reg_artifacts:
    steps:
      - name: Inform system that an artifact version was created
        uses: cloudbees-io/register-build-artifact@v1
        with:
          name: "cbpautomation/python-hello-world-docker"
          version: "06.10.34"
          url: "docker.io/cbpautomation/python-hello-world-docker:06.10.34"
          digest: "sha256:1d5d6c656b9745a3a7b88de82ba0768862b4df0c5debda25bb979def69613d75"
          
      - name: success_valid_env_reg_artifact
        uses: cloudbees-io/register-deployed-artifact@v1
        with:
          name: "cbpautomation/python-hello-world-docker"
          version: "06.10.34"
          digest: "sha256:1d5d6c656b9745a3a7b88de82ba0768862b4df0c5debda25bb979def69613d75"
          url: "docker.io/cbpautomation/python-hello-world-docker:06.10.34"
          target-environment: "QA"

