apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: RegisterDeployedArtifact
on:
  push:
    branches:
      - "**"
  workflow_dispatch:
jobs:
  env_reg_artifacts:
    steps:
      - name: success_valid_env_reg_artifact
        uses: cloudbees-io/register-deployed-artifact@v1
        with:
          name: "cbpautomation/python-hello-world-docker"
          version: "0.0.465"
          url: "docker.io/cbpautomation/python-hello-world-docker:0.0.465"
          digest: "sha256:0a6c4ac6b22816a7744f1aacc22710555a5aecbbc338387400fa56867d4a9736"
          target-environment: "PREPROD"