apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: RegisterDeployedArtifact
on:
  workflow_dispatch:
jobs:
  env_reg_artifacts:
    steps:
      - name: Inform system that an artifact version was created
        uses: cloudbees-io/register-build-artifact@v1
        with:
          name: "cbpautomation/python-hello-world-docker"
          version: "13.10.41"
          url: "docker.io/cbpautomation/python-hello-world-docker:13.10.41"
          digest: "sha256:5d0bfb0d1b3676e272a97d1720eb587d307b17a34157038f5592363401a743a3"
          
      - name: success_valid_env_reg_artifact
        uses: cloudbees-io/register-deployed-artifact@v1
        with:
          name: "cbpautomation/python-hello-world-docker"
          version: "13.10.41"
          digest: "sha256:5d0bfb0d1b3676e272a97d1720eb587d307b17a34157038f5592363401a743a3"
          url: "docker.io/cbpautomation/python-hello-world-docker:13.10.41"
          target-environment: "QA"

