apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: RegisterDeployedArtifact
on:
  workflow_dispatch:
jobs:
  env_reg_artifacts:
    steps:
      - name: success_valid_env_reg_artifact
        uses: cloudbees-io/register-deployed-artifact@v1
        with:
          name: "cbpautomation/python-hello-world-docker"
          version: "21.17.32"
          digest: "sha256:2e5984131af4bc34794114702e0948e6c44e4c83686a39a5f49897a63dd22775"
          url: "docker.io/cbpautomation/python-hello-world-docker:21.17.32"
          target-environment: "QA"

