apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: RegisterDeployedArtifact
on:
  workflow_dispatch:
jobs:
  env_reg_artifacts:
    steps:
      - name: success_valid_env_reg_artifact
        uses: cloudbees-io/register-deployed-artifact@v1
        with:
          name: "cbpautomation/python-hello-world-docker"
          version: "28.16.31"
          digest: "sha256:7b87a89ebd306a196bada560a1f41c5371274be892e19f910627f92e7287f3c1"
          url: "docker.io/cbpautomation/python-hello-world-docker:28.16.31"
          target-environment: "QA"

