apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: RegisterDeployedArtifact
on:
  workflow_dispatch:
jobs:
  env_reg_artifacts:
    steps:
      - name: success_valid_env_reg_artifact
        uses: cloudbees-io/register-deployed-artifact@v1
        with:
          name: "cbpautomation/python-hello-world-docker"
          version: "09.12.56"
          digest: "sha256:2661b51463c198dad30b89cb2bcaef6aa46f5265f7a6fa6291b928bf6c999dad"
          url: "docker.io/cbpautomation/python-hello-world-docker:09.12.56"
          target-environment: "QA"

