apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: RegisterDeployedArtifact
on:
  workflow_dispatch:
jobs:
  env_reg_artifacts:
    steps:
      - name: Inform system that an artifact version was created
        uses: cloudbees-io/register-build-artifact@v1
        with:
          name: "cbpautomation/python-hello-world-docker"
          version: "13.10.28"
          url: "docker.io/cbpautomation/python-hello-world-docker:13.10.28"
          digest: "sha256:272a7341f625d8ddb66f24ef9611758bea6ad24759b04db908a584e5435440ec"
          
      - name: success_valid_env_reg_artifact
        uses: cloudbees-io/register-deployed-artifact@v1
        with:
          name: "cbpautomation/python-hello-world-docker"
          version: "13.10.28"
          digest: "sha256:272a7341f625d8ddb66f24ef9611758bea6ad24759b04db908a584e5435440ec"
          url: "docker.io/cbpautomation/python-hello-world-docker:13.10.28"
          target-environment: "QA"

