apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: RegisterDeployedArtifact
on:
  workflow_dispatch:
jobs:
  env_reg_artifacts:
    steps:
      - name: success_valid_env_reg_artifact
        uses: cloudbees-io/register-deployed-artifact@v1
        with:
          name: "cbpautomation/python-hello-world-docker"
          version: "17.04.26"
          digest: "sha256:46fbd11981a735262ca9626248be0763a1af60509fd2b33684b51090eeb48fc5"
          url: "docker.io/cbpautomation/python-hello-world-docker:17.04.26"
          target-environment: "QA"

