apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: RegisterDeployedArtifact
on:
  workflow_dispatch:
jobs:
  env_reg_artifacts:
    steps:
      - name: Inform system that an artifact version was created
        uses: cloudbees-io/register-build-artifact@v1
        with:
          name: "cbpautomation/python-hello-world-docker"
          version: "29.17.36"
          url: "docker.io/cbpautomation/python-hello-world-docker:29.17.36"
          digest: "sha256:db1543c6f186b0dd21fdb6d687b057aa3f7fecb789eeaa065ee2a5e3fbbaad89"
          
      - name: success_valid_env_reg_artifact
        uses: cloudbees-io/register-deployed-artifact@v1
        with:
          name: "cbpautomation/python-hello-world-docker"
          version: "29.17.36"
          digest: "sha256:db1543c6f186b0dd21fdb6d687b057aa3f7fecb789eeaa065ee2a5e3fbbaad89"
          url: "docker.io/cbpautomation/python-hello-world-docker:29.17.36"
          target-environment: "QA"

