apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: RegisterDeployedArtifact
on:
  workflow_dispatch:
jobs:
  env_reg_artifacts:
    steps:
      - name: Inform system that an artifact version was created
        uses: cloudbees-io/register-build-artifact@v1
        with:
          name: "cbpautomation/python-hello-world-docker"
          version: "06.06.17"
          url: "docker.io/cbpautomation/python-hello-world-docker:06.06.17"
          digest: "sha256:97dc7be8e76ca99442e0fa7a04477616198e100ff0c6352fad2a2ed9d3c58c38"
          
      - name: success_valid_env_reg_artifact
        uses: cloudbees-io/register-deployed-artifact@v1
        with:
          name: "cbpautomation/python-hello-world-docker"
          version: "06.06.17"
          digest: "sha256:97dc7be8e76ca99442e0fa7a04477616198e100ff0c6352fad2a2ed9d3c58c38"
          url: "docker.io/cbpautomation/python-hello-world-docker:06.06.17"
          target-environment: "QA"

