apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: RegisterDeployedArtifact
on:
  workflow_dispatch:
jobs:
  env_reg_artifacts:
    steps:
      - name: Inform system that an artifact version was created
        uses: cloudbees-io/register-build-artifact@v1
        with:
          name: "cbpautomation/python-hello-world-docker"
          version: "23.10.47"
          url: "docker.io/cbpautomation/python-hello-world-docker:23.10.47"
          digest: "sha256:07c0163cea3241dde9e7028b8a34f2e1808ed6d2d75abcf1fd95d61bfa7a90aa"
          
      - name: success_valid_env_reg_artifact
        uses: cloudbees-io/register-deployed-artifact@v1
        with:
          name: "cbpautomation/python-hello-world-docker"
          version: "23.10.47"
          digest: "sha256:07c0163cea3241dde9e7028b8a34f2e1808ed6d2d75abcf1fd95d61bfa7a90aa"
          url: "docker.io/cbpautomation/python-hello-world-docker:23.10.47"
          target-environment: "QA"

