apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: RegisterDeployedArtifact
on:
  workflow_dispatch:
jobs:
  env_reg_artifacts:
    steps:
      - name: success_valid_env_reg_artifact
        uses: cloudbees-io/register-deployed-artifact@v1
        with:
          name: "cbpautomation/python-hello-world-docker"
          version: "21.04.30"
          digest: "sha256:9dcb61d0f6766a34cc2e1cb732fffa9a4e0d1e1892b50670f3aaaff9c3fa97f9"
          url: "docker.io/cbpautomation/python-hello-world-docker:21.04.30"
          target-environment: "QA"

