apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: Foo Workflow
on:
  workflow_dispatch:
jobs:
  call_bar_workflow:
    uses: cbp-test-QA-automation/qa-python-helloworld/.cloudbees/workflows/callable-workflow-3b9d62a3-640a-4328-b872-bfa81ae42c90.yaml
    