apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: My workflow

on:
  workflow_dispatch:

jobs:
  build:
    steps:
    - name: Dispatch workflows
      uses: https://github.com/cloudbees-io/workflows-dispatch@v1
      with:
        workflows-dispatch-file: dispatch_requests.json
        token: "${{ secrets.CBP_API_PAT }}"
